Parameters:
  InstanceProfileName:
    Type: String
  SecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
  SubnetId:
    Type: AWS::EC2::Subnet::Id
  AmiId:
    Type: String
  InstanceType:
    Type: String
  Name:
    Type: String
  IsPublicIpAddressEnabled:
    Type: String
    Default: "false"
  ECSClusterName:
    Type: String
  PlacementConstraintContext:
    Type: String

Resources:
  ContainerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref AmiId
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref InstanceProfileName
      NetworkInterfaces:
        - AssociatePublicIpAddress: !Ref IsPublicIpAddressEnabled
          DeviceIndex: "0"
          GroupSet:
            - Ref: SecurityGroupId
          SubnetId:
            Ref: SubnetId
      UserData:
        Fn::Base64:
          !Sub |
            #!/usr/bin/env bash
            cat << EOF >> /etc/ecs/ecs.config
            ECS_CLUSTER=${ECSClusterName}
            ECS_INSTANCE_ATTRIBUTES={"context":"${PlacementConstraintContext}"}
            EOF
      Tags:
        - Key: Name
          Value: !Ref Name

Outputs:
  Ipv4Addr:
    Value: !GetAtt ContainerInstance.PrivateIp