Parameters:
  Path:
    Type: String

Resources:
  # Roles
  ECSTaskExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: !Ref Path
  EC2ContainerInstanceRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Path: !Ref Path

  # Policies
  ECSTaskExecutionRolePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: ECSTaskExecutionRolePolicy
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "ecr:GetAuthorizationToken"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: '*'
      Roles:
        - !Ref ECSTaskExecutionRole

  # Instance Profile
  EC2ContainerInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: !Ref Path
      Roles:
        - Ref: EC2ContainerInstanceRole

Outputs:
  ECSTaskExecutionRoleArn:
    Value: !GetAtt ECSTaskExecutionRole.Arn
  EC2ContainerInstanceProfileName:
    Value: !Ref EC2ContainerInstanceProfile